### ISSUE TITLE
Completely broken

### ISSUE THREAD

**Issue by CuteWaterBeary** [Narazaka/BoneSelector#1]
This does not show up on the menu. Adding it using git #1.0.0 prevents Unity from downloading it. Dragging the folder in makes it not recognized. The version on booth.pm is not even a .unitypackage in the archive. Adding it via git without #1.0.0 allows it to get downloaded but it still fails to load or show on the menu. 

You have some paid products on booth that I was interested in but are they the same quality as this?

**Comment by Narazaka** [comment]
This is a partially extracted version of a package in Booth, a library file, not the type that brings up a tool window.

**Comment by Narazaka** [comment]
And this is something that was left until the VPM environment was ready. I have never declared this a release.

**Comment by Narazaka** [comment]
> You have some paid products on booth that I was interested in but are they the same quality as this?

I recommend that you read the description carefully before using my products.

**Comment by CuteWaterBeary** [comment]
I guess I was confused on how to use this.
